config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :posts, only: [:index, :show, :destroy]
    resources :comments, only: [:destroy]
    resources :reports, only: [:index, :show, :update]

    resources :members, only: [:index, :show, :update] do
      member do
        patch :deactivate
        patch :reactivate
      end
    end
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :public do
    get 'sessions/new'
  end

  devise_for :members, controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  devise_scope :member do
    post "members/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  
  scope module: :public do
    root 'homes#top'

    get 'how_to', to: 'homes#how_to'
    get '/members/edit_profile', to: 'members#edit_profile', as: 'edit_profile'
    patch '/members/update_profile', to: 'members#update_profile', as: 'update_profile'
    patch '/members/withdraw', to: 'members#withdraw', as: 'withdraw'
    get '/members/unsubscribe', to: 'members#unsubscribe', as: 'unsubscribe'
    get '/members/saved_posts', to: 'members#saved_posts', as: 'saved_posts'

    resources :members, only: [:show] do
      member do
        get :followers          
        get :followings         
      end
      resource :relationship, only: [:create, :destroy]
      resources :reports, only: [:new, :create]
    end

    resources :notifications, only: :index

    resources :posts do
      collection do
        get :followings
      end
      resources :comments, only: [:create, :destroy]
      resource :saved_post, only: [:create, :destroy]
    end
  end
end

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" class="alert alert-danger text-center mx-auto w-100 mt-4 mb-4 py-4" data-turbo-cache="false">
    <h2 class="fs-5 fw-bold mb-3">
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul class="mb-0 list-unstyled">
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_form_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger text-center w-100 mb-5">
    <h2 class="fs-5 fw-bold">入力内容に不備があるようです。</h2>
    <ul class="mb-0 list-unstyled">
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_member_summary.html.erb
<% if current_member&.guest? %>
  <div class="text-decoration-none link-dark d-flex align-items-center">
    <%= image_tag member.profile_image.variant(resize_to_fill: [50, 50]), alt: "プロフィール画像", class: "rounded-circle me-3" %>
    <span class="text-break"><%= member.name %></span>
  </div>
<% else %>
  <%= link_to member_path(member), class: "text-decoration-none link-dark d-flex align-items-center" do %>
    <%= image_tag member.profile_image.variant(resize_to_fill: [50, 50]), alt: "プロフィール画像", class: "rounded-circle me-3" %>
    <span class="text-break"><%= member.name %></span>
  <% end %>
<% end %>

app/views/shared/_notification_icon.html.erb
<% unread_count = unchecked_notifications.count %>

<%= link_to notifications_path, class: "nav-link text-body d-flex align-items-center sidebar-link-large" do %>
  <i class="fa-regular fa-bell me-4"></i>
  <span>通知</span>
  <% if unread_count > 0 %>
    <span class="badge rounded-pill bg-danger ms-2">
      <%= unread_count %>
    </span>
  <% end %>
<% end %>