config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :posts, only: [:index, :show, :destroy]
    resources :comments, only: [:destroy]
    resources :reports, only: [:index, :show, :update]

    resources :members, only: [:index, :show, :update] do
      member do
        patch :deactivate
        patch :reactivate
      end
    end
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :public do
    get 'sessions/new'
  end

  devise_for :members, controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  devise_scope :member do
    post "members/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  
  scope module: :public do
    root 'homes#top'

    get 'how_to', to: 'homes#how_to'
    get '/members/edit_profile', to: 'members#edit_profile', as: 'edit_profile'
    patch '/members/update_profile', to: 'members#update_profile', as: 'update_profile'
    patch '/members/withdraw', to: 'members#withdraw', as: 'withdraw'
    get '/members/unsubscribe', to: 'members#unsubscribe', as: 'unsubscribe'
    get '/members/saved_posts', to: 'members#saved_posts', as: 'saved_posts'

    resources :members, only: [:show] do
      member do
        get :followers          
        get :followings         
      end
      resource :relationship, only: [:create, :destroy]
      resources :reports, only: [:new, :create]
    end

    resources :notifications, only: :index

    resources :posts do
      collection do
        get :followings
      end
      resources :comments, only: [:create, :destroy]
      resource :saved_post, only: [:create, :destroy]
    end
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :posts

  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :restrict_to_admin!
  before_action :set_genre, only: [:edit, :update, :destroy]
  
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create 
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path, notice: "ジャンルを追加しました。"
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
  end

  def update
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  def destroy
    @genre.destroy
    redirect_to admin_genres_path, notice: "ジャンルを削除しました。"
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

  def set_genre
    @genre = Genre.find(params[:id])
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/_form_field.html.erb
<div>
  <%= f.label :name, "ジャンル名", class: "form-label fs-4 mb-0" %>
</div>
<div class="w-25">
  <%= f.text_field :name, placeholder: "ジャンル名", class: "form-control form-control-lg w-100" %>
</div>

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="w-50 mx-auto mb-4">
    <%= render 'shared/form_error_messages', object: @genre %>
  </div>

  <h3 class="text-center mb-4 mt-4 genre-heading">ジャンル編集</h3>

  <%= form_with model: @genre, url: admin_genre_path(@genre) do |f| %>
    <div class="d-flex justify-content-center align-items-center gap-3 mb-4">
      <%= render 'form_field', f: f %>
      <div>
        <%= f.submit "変更を保存", class: "btn btn-success btn-lg" %>
      </div>
    </div>
  <% end %>
</div>
    

app/views/admin/genres/index.html.erb
<div class="container mt-4 mb-4">
  <div class="w-50 mx-auto mb-4">
    <%= render 'shared/form_error_messages', object: @genre %>
  </div>

  <%= form_with model: @genre, url: admin_genres_path do |f| %>
    <div class="d-flex justify-content-center align-items-center gap-3 mb-4">
      <%= render 'form_field', f: f %>
      <div>
        <%= f.submit "新規登録", class: "btn btn-success btn-lg" %>
      </div>
    </div>
  <% end %>
</div>

<div class="mt-5">
  <table class="table table-bordered w-25 mx-auto align-middle ext-nowrap">
    <thead class="table-success">
      <tr>
        <th class="fw-normal">ジャンル名</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @genres.each do |genre| %>
        <tr>
          <td><%= genre.name %></td>
          <td>
            <%= link_to "編集", edit_admin_genre_path(genre), class: "btn btn-outline-success" %>
          </td>
          <td>
            <%= link_to "削除", admin_genre_path(genre), method: :delete, class: "btn btn-outline-danger" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>