config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :posts, only: [:index, :show, :destroy]
    resources :comments, only: [:destroy]
    resources :reports, only: [:index, :show, :update]

    resources :members, only: [:index, :show, :update] do
      member do
        patch :deactivate
        patch :reactivate
      end
    end
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :public do
    get 'sessions/new'
  end

  devise_for :members, controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  devise_scope :member do
    post "members/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  
  scope module: :public do
    root 'homes#top'

    get 'how_to', to: 'homes#how_to'
    get '/members/edit_profile', to: 'members#edit_profile', as: 'edit_profile'
    patch '/members/update_profile', to: 'members#update_profile', as: 'update_profile'
    patch '/members/withdraw', to: 'members#withdraw', as: 'withdraw'
    get '/members/unsubscribe', to: 'members#unsubscribe', as: 'unsubscribe'
    get '/members/saved_posts', to: 'members#saved_posts', as: 'saved_posts'

    resources :members, only: [:show] do
      member do
        get :followers          
        get :followings         
      end
      resource :relationship, only: [:create, :destroy]
      resources :reports, only: [:new, :create]
    end

    resources :notifications, only: :index

    resources :posts do
      collection do
        get :followings
      end
      resources :comments, only: [:create, :destroy]
      resource :saved_post, only: [:create, :destroy]
    end
  end
end

app/views/layouts/_admin_header.html.erb
<header class="header">
  <nav class="navbar navbar-expand-lg bg-light navbar-light">
    <div class="container-fluid px-5">
      <%= link_to admin_posts_path, class: "navbar-brand" do %>
        <%= image_tag "tsunagari_logo_flower.png", alt: "つながり広場のロゴ", class: "header-logo-img" %>
      <% end %>
      <div class="navbar-collapse d-flex justify-content-end">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <%= link_to "投稿一覧", admin_posts_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "登録者一覧", admin_members_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "通報一覧", admin_reports_path, class: "nav-link" %>
          </li> 
          <li class="nav-item">
            <%= link_to "ジャンル一覧", admin_genres_path, class: "nav-link" %>
          </li> 
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_flash_messages.html.erb
<% if notice %>
  <div class="container">
    <div class="d-flex justify-content-center mt-4 mb-2">
      <div class="alert alert-success text-center w-50">
        <%= notice %>
      </div>
    </div>
  </div>
<% end %>

<% if alert %>
  <div class="container">
    <div class="d-flex justify-content-center mt-4 mb-2">
      <div class="alert alert-danger text-center w-50">
        <%= alert %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_guest_header.html.erb
<header class="header">
  <nav class="navbar navbar-expand-lg bg-light navbar-light">
    <div class="container-fluid px-5">
      <%= link_to posts_path, class: "navbar-brand" do %>
        <%= image_tag "tsunagari_logo_flower.png", alt: "つながり広場のロゴ", class: "header-logo-img" %>
      <% end %>
      <button class="navbar-toggler d-flex align-items-center d-lg-none" data-bs-toggle="collapse" data-bs-target="#navbarNav">
        <span class="navbar-toggler-icon me-2"></span> 項目の一覧
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <%= link_to "投稿を検索する", posts_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "つながり広場へ戻る", destroy_member_session_path, method: :delete, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_hamburger_menu.html.erb
<button class="btn btn-outline-success text-start fw-bold d-xl-none mb-2 mt-3 ms-3" data-bs-toggle="collapse" data-bs-target="#hamburgerMenu">
  <i class="fa-solid fa-bars me-2"></i> 項目の一覧
</button>

<div id="hamburgerMenu" class="collapse p-3">
  <%= link_to new_post_path, class: "nav-link text-body sidebar-link-large mb-3" do %>
    <i class="fa-regular fa-pen-to-square me-3"></i> 新規投稿
  <% end %>

  <%= link_to member_path(current_member), class: "nav-link text-body sidebar-link-large mb-3" do %>
    <i class="fa-regular fa-file-lines me-3"></i> 自分の投稿
  <% end %>
  
  <%= link_to saved_posts_path, class: "nav-link text-body sidebar-link-large mb-3" do %>
    <i class="fa-regular fa-bookmark me-3"></i> 保存した投稿
  <% end %>

  <%= link_to followings_posts_path, class: "nav-link text-body sidebar-link-large mb-3" do %>
    <i class="fa-regular fa-thumbs-up me-3"></i> 応援している人の投稿
  <% end %>

  <%= link_to posts_path, class: "nav-link text-body sidebar-link-large mb-3" do %>
    <i class="fa-solid fa-magnifying-glass me-3"></i> 気になる投稿を検索
  <% end %>

  <%= render 'shared/notification_icon' %>

  <%= link_to member_path(current_member), class: "nav-link text-body sidebar-link-large mb-3 mt-3" do %>
    <i class="fa-regular fa-user me-3"></i> マイページ
  <% end %>
  
  <%= link_to how_to_path, class: "nav-link text-body sidebar-link-large mb-3 mt-3" do %>
   <i class="fa-solid fa-book me-3"></i> サイトの使い方
  <% end %>

  <%= link_to destroy_member_session_path, method: :delete, class: "nav-link text-body sidebar-link-large mb-3" do %>
    <i class="fa-solid fa-house me-2"></i> ホームに戻る
  <% end %>
</div>

app/views/layouts/_header.html.erb
<header class="header">
  <nav class="navbar navbar-expand-lg bg-light navbar-light">
    <div class="container-fluid px-5">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "tsunagari_logo_flower.png", alt: "つながり広場のロゴ", class: "header-logo-img" %>
      <% end %>
      <button class="navbar-toggler d-flex align-items-center d-lg-none" data-bs-toggle="collapse" data-bs-target="#navbarNav">
        <span class="navbar-toggler-icon me-2"></span> 項目の一覧
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <%= link_to "はじめての方", new_member_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "マイページに入る", new_member_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "見学してみる", members_guest_sign_in_path, class: "nav-link", method: :post %>
          </li> 
          <li class="nav-item">
            <%= link_to "サイトの使い方", how_to_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "つながり広場へ", root_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_sidebar.html.erb
<div class="d-flex justify-content-start my-3 ps-4 sidebar-logo">
  <%= link_to root_path, class: "navbar-brand " do %>
    <%= image_tag "tsunagari_logo_flower.png", alt: "つながり広場のロゴ", class: "sidebar-logo-img" %>
  <% end %>
</div>
<div class="flex-column nav">
  <%= link_to new_post_path, class: "nav-link text-body sidebar-link-large" do %>
    <i class="fa-regular fa-pen-to-square me-3"></i> 新規投稿
  <% end %>

  <%= link_to member_path(current_member), class: "nav-link text-body sidebar-link-large" do %>
    <i class="fa-regular fa-file-lines me-3"></i> 自分の投稿
  <% end %>
  
  <%= link_to saved_posts_path, class: "nav-link text-body sidebar-link-large" do %>
    <i class="fa-regular fa-bookmark me-3"></i> 保存した投稿
  <% end %>

  <%= link_to followings_posts_path, class: "nav-link text-body sidebar-link-large" do %>
    <i class="fa-regular fa-thumbs-up me-3"></i> 応援している人の投稿
  <% end %>

  <%= link_to posts_path, class: "nav-link text-body sidebar-link-large" do %>
    <i class="fa-solid fa-magnifying-glass me-3"></i> 気になる投稿を検索
  <% end %>

  <%= render 'shared/notification_icon' %>

  <%= link_to member_path(current_member), class: "nav-link text-body sidebar-link-large" do %>
    <i class="fa-regular fa-user me-3"></i> マイページ
  <% end %>
  
  <%= link_to how_to_path, class: "nav-link text-body sidebar-link-large" do %>
   <i class="fa-solid fa-book me-3"></i> サイトの使い方 
  <% end %>

  <%= link_to destroy_member_session_path, method: :delete, class: "nav-link text-body sidebar-link-large" do %>
    <i class="fa-solid fa-house me-2"></i> ホームに戻る
  <% end %>
</div><%# flex-column nav %>

     

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>つながり広場</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <script src="https://kit.fontawesome.com/c4e027a92c.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if member_signed_in? && current_member.guest? %>
      <%= render 'layouts/guest_header' %>
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    <% elsif member_signed_in? %>
      <div class="container layout">
        <div class="row">
          <div class="col-xl-3 d-none d-xl-block sidebar-left border-end">
            <%= render 'layouts/sidebar' %>
          </div>
          <div class="col-xl-9 col-12 px-3">
            <div class="d-xl-none mb-2">
              <%= render 'layouts/hamburger_menu' %>
            </div>
            <%= yield %>
          </div>
        </div>
      </div>
    <% elsif admin_signed_in? %>
      <%= render 'layouts/admin_header' %>
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    <% else %>
      <%= render 'layouts/header' %>
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    <% end %>
  </body>
</html>